# Generated by Django 3.0.5 on 2021-05-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_d', models.CharField(db_index=True, max_length=255)),
                ('published_date', models.DateField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('actual_link', models.CharField(max_length=255)),
            ],
        ),
    ]
