# Generated by Django 3.0.5 on 2021-05-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubedata',
            old_name='video_d',
            new_name='video_id',
        ),
    ]
